name: Install uv & just
description: Install uv & just using the community actions
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.30"

    - name: Install just
      uses: extractions/setup-just@v2
      with:
        just-version: 1.5.0
